config/routes.rb
Rails.application.routes.draw do
  resources :products do
    member do
      get :customers
    end
    resources :buy_nows, only: [ :show ] do
      collection do
        get :purchase
        post :confirm_purchase
      end
    end
  end

  resources :carts, only: [ :show ] do
    collection do
      post :add
      delete :clear
      get :current
      delete :remove_item
      get :purchase_all
      post :confirm_purchase_all
    end
  end

  resources :buy_nows do
    member do
      get :qr_code
      patch :confirm_payment
    end
  end

  resource :user, only: [] do
    post :drink
  end

  resources :accounts, controller: "accounts"

  get "check_out_beer", to: "beers#check_out_beer", as: :check_out_beer
  post "check_out_beer", to: "beers#check_out", as: :check_out

  get "sign_up", to: "registrations#new", as: :sign_up
  post "sign_up", to: "registrations#create"

  get "additional_info", to: "registrations#additional_info"

  get "sign_in", to: "sessions#new", as: :new_session
  post "sign_in", to: "sessions#create"

  get "password", to: "passwords#edit", as: :edit_password
  patch "password", to: "passwords#update"

  delete "sign_out", to: "sessions#destroy", as: :sign_out
  get "sign_out", to: "sessions#sign_out_modal", as: :sign_out_modal

  get "password/reset", to: "password_resets#new"
  post "password/reset", to: "password_resets#create"
  get "password/reset/edit", to: "password_resets#edit"
  patch "password/reset/edit", to: "password_resets#update"

  get "users", to: "users#index"

  get "beers", to: "beers#index"

  root "home#index"
end

app/models/user.rb
class User < ApplicationRecord
  has_many :buy_nows
  has_many :products
  has_one_attached :qr_code

  has_secure_password

  validates :email,
            presence: { message: "กรุณากรอกอีเมล" },
            uniqueness: { message: "อีเมลนี้ถูกใช้งานแล้ว" },
            format: { with: /\A[^@\s]+@[^@\s]+\z/, message: "รูปแบบอีเมลไม่ถูกต้อง" }

  validates :password,
            presence: { message: "กรุณากรอกรหัสผ่าน" },
            length: { minimum: 8, maximum: 16, message: "รหัสผ่านต้องมีความยาวระหว่าง 8-16 ตัวอักษร" },
            format: {
              with: /\A(?=.*[a-zA-Z])(?=.*\d)(?=.*[!"#$%&'()*+,-.\/:;<=>?@[\\]^_`{|}~])[A-Za-z\d!"#$%&'()*+,-.\/:;<=>?@[\\]^_`{|}~]{8,16}\z/,
              message: "รหัสผ่านต้องประกอบด้วยตัวอักษร ตัวเลข และสัญลักษณ์พิเศษ"
            },
            on: :create

  validates :beer_balance, numericality: { greater_than_or_equal_to: 0, message: "ต้องมากกว่าหรือเท่ากับ 0" }

  def deposit(amount)
    return false if amount <= 0
    increment!(:beer_balance, amount)
  end

  def withdraw(amount)
    return false if amount <= 0 || amount > beer_balance
    decrement!(:beer_balance, amount)
  end

  def drink_beer
    if beer_balance > 0
      update(beer_balance: beer_balance - 1)
      true
    else
      false
    end
  end

  validates :first_name,
            presence: { message: "กรุณากรอกชื่อ" },
            format: { with: /\A[ก-ฮ\u0E30-\u0E3A\u0E40-\u0E4E a-zA-Z]+\z/, message: "กรุณากรอกเฉพาะตัวอักษรไทยหรืออังกฤษ" },
            on: :update, if: :first_name_changed?

  validates :last_name,
            presence: { message: "กรุณากรอกนามสกุล" },
            format: { with: /\A[ก-ฮ\u0E30-\u0E3A\u0E40-\u0E4E a-zA-Z]+\z/, message: "กรุณากรอกเฉพาะตัวอักษรไทยหรืออังกฤษ" },
            on: :update, if: :last_name_changed?

  validates :phone,
            presence: { message: "กรุณาเบอร์โทรศัพท์" },
            length: { minimum: 10, maximum: 10 },
            format: { with: /\A\d{10}\z/, message: "เบอร์โทรศัพท์ 10 หลัก" },
            on: :update, if: :phone_changed?

  validates :prompt_pay,
            presence: { message: "กรุณากรอกพร้อมเพย์" },
            format: { with: /\A\d{10}\z|\A\d{13}\z/, message: "หมายเลขโทรศัพท์ 10 หลัก, หมายเลขบัตรประชาชน 13 หลัก" },
            on: :update, if: :prompt_pay_changed?

  validates :address,
            presence: { message: "กรุณากรอกที่อยู่" },
            on: :update, if: :address_changed?

  before_create :set_default_beer_balance

  private

  def set_default_beer_balance
    self.beer_balance = 0 if beer_balance.nil?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = Current.user
  end

  def drink
    if current_user.drink_beer
      redirect_to user_dashboard_path, notice: "ดื่มเบียร์แล้ว! 🍻 เหลือ #{current_user.beer_balance} แก้ว",
      data: { testid: "user-drink-beer-success-notice" }
    else
      redirect_to user_dashboard_path, alert: "ไม่มีเบียร์เหลือแล้ว! ไปเติมเลย! 🍺",
      data: { testid: "user-drink-beer-error-notice" }
    end
  end
end

app/views/users/index.html.erb
<div class="flex flex-col items-center w-full max-w-md mx-auto bg-white shadow-lg rounded-lg p-6 py-2">

  <div class="w-full">
    <div class="py-2 w-full flex justify-between items-center">
      <h1 class="text-2xl font-semibold flex items-center text-black" data: { testid: "user-index-title" }>
        <span class="mr-2">
          🧑
        </span>
        บัญชีผู้ใช้
      </h1>
      <% if @user %>
        <span class="text-gray-600" data: { testid: "user-email" }><%= @user.email %></span>
      <% end %>
    </div>

      <%= link_to accounts_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-gray-50 rounded-md hover:bg-gray-100 transition-colors mt-4",
      data: { testid: "accounts-path-button" } do %>
        <span class="text-black mr-3">✏️</span>
        &nbsp;
        <span>บัญชีผู้ใช้</span>
      <% end %>

      <%= link_to products_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-gray-50 rounded-md hover:bg-gray-100 transition-colors mt-4",
      data: { testid: "products-path-button" } do %>
        <span class="text-black mr-3">📦</span>
        &nbsp;
        <span>สินค้าของฉัน</span>
      <% end %>

      <%= link_to buy_nows_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-gray-50 rounded-md hover:bg-gray-100 transition-colors mt-4",
      data: { testid: "buy-nows-path-button" } do %>
        <span class="text-black mr-3">🧾</span>
        &nbsp;
        <span>รายการสินค้าที่ซื้อ</span>
      <% end %>

      <%= link_to edit_password_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-gray-50 rounded-md hover:bg-gray-100 transition-colors mt-4",
      data: { testid: "edit-password-path-button" } do %>
        <span class="text-black mr-3">🗝️</span>
        &nbsp;
        <span>เปลี่ยนรหัสผ่าน</span>
      <% end %>

      <%= link_to root_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-blue-200 rounded-md hover:bg-blue-300 transition-colors mt-4",
      data: { testid: "root-path-button" } do %>
        <span class="text-black mr-3">🏠</span>
        &nbsp;
        <span>หน้าหลัก ODDS ODDS SHOP</span>
      <% end %>

      <%= link_to sign_out_modal_path, class: "text-2xl w-full px-4 py-2 flex items-center p-3 bg-red-50 rounded-md hover:bg-red-100 transition-colors mt-8", data: { turbo_frame: "modal",
      testid: "sign-out-modal-button" } do %>
        <span class="text-red-600 mr-3">⬅️</span>
        &nbsp;
        <span class="text-red-600">ออกจากระบบ</span>
      <% end %>
    </div>
  </div>
</div>

<%= turbo_frame_tag "modal" %>